# this workflow will run on every pr to make sure the project is following the guidelines

# after labeler, run other actions with strict permissions
name: CI

on:
  pull_request:
    branches: ["*"]
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: |
          cp .env.example .env
          pnpm run lint
        shell: bash

  # check-changeset:
  #   runs-on: ubuntu-latest
  #   name: Check Changeset
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: ./.github/actions/setup

  #     - name: Check and Validate Changes
  #       run: |
  #         git fetch origin main:main
  #         pnpm changeset status --since origin/main
  #         exit_status=$?
  #         if [[ $exit_status -eq 0 ]]; then
  #           echo "Changeset validation succeeded."
  #         else
  #           echo "Changeset validation failed."
  #         fi
  #       shell: bash

  prettier:
    runs-on: ubuntu-latest
    name: Run Prettier
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - run: pnpm format:check
        shell: bash

  tsc:
    runs-on: ubuntu-latest
    name: Run Typechecker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - run: pnpm typecheck
        shell: bash
